### ISSUE TITLE
Record, playback, and/or drawing sequence?

### ISSUE THREAD

**Issue by brylie** [JohnMcLear/draw#187] opened 2015-05-20 09:18 UTC
I am researching an [idea for Khan Academy](https://khanacademy.zendesk.com/hc/communities/public/questions/202919550-Time-based-animated-learning-resource-creator), regarding animated educational resources. How would one record, playback, and edit an etherdraw drawing, in non-video form. For example, given an existing drawing, the stages of the drawing would be editable and the playback sequence, speed, and direction could be changed arbitrarily.

**Comment by JohnMcLear** [comment] 2015-05-20 09:39
Relatively easily but it would require some development work.  Look at how the data is stored in the database.
----- Reply message -----

**Comment by brylie** [comment] 2015-05-21 07:10
Thanks for your quick response. Is there a particular file and line(s) of code that I can review? I have taken a look at the [db.js](https://github.com/JohnMcLear/draw/blob/master/src/util/db.js), but didn't see a schema.

**Comment by JohnMcLear** [comment] 2015-05-21 07:35
It's a key value store. Couldn't be more simple
----- Reply message -----

**Comment by JohnMcLear** [comment] 2015-06-07 23:10
Duplicate of #155

**Closed** 2015-06-07 23:11 UTC

**Comment by theoryshaw** [comment] 2015-06-08 19:19
+1

**Comment by JohnMcLear** [comment] 2015-06-08 23:14
I put the required logic needed for this on https://github.com/JohnMcLear/draw/tree/timeslider

It's about a day or two doing UX/UI things which imho would be easy now the logic is available.

If someone wants to sponsor this I'd be happy to do the work else someone else can jump in and do the low hanging fruits.

**Comment by brylie** [comment] 2015-06-09 01:18
I can take a task, with some guidance. What would be helpful for me to do?

**Comment by JohnMcLear** [comment] 2015-06-10 10:19
Checkout the branch, it should be obvious what needs doing..  Just creating a list of things to do would be useful, ones off the top of my head..

 - [ ] Icon
 - [ ] Styling
 - [ ] Documentation
 - [ ] Sliderbar to move to different locations
 - [ ] Preview images on slider bar
 - [ ] Store time deltas with paths and retrieve paths based on deltas
